---
# tasks file for mighty-common
- name: Install common packages for everyday use
  apt: pkg={{ item }} install_recommends=yes state=latest cache_valid_time=3600 update_cache=yes
  with_items:
      - screen
      - sudo
      - arping
      - tshark
      - mc
      - unzip
      - vim
      - logwatch
      - logrotate
      - bzip2
      - fail2ban
      - iptables
      - iptables-persistent
      - p7zip
      - p7zip-full
      - p7zip-rar
      - pwgen
  tags:
      - mightydok-common

- name: Set timezone to Europe/Moscow
  timezone: name="Europe/Moscow"
  tags:
      - mightydok-common

- name: Add deploy group
  group: name=deploy
  tags:
      - mightydok-common

- name: Add deploy user
  user: name=deploy group=deploy createhome=yes shell=/bin/bash
  tags:
      - mightydok-common

- name: Add sudoers for deploy user
  template:
    src: 10-deploy.j2
    dest: /etc/sudoers.d/10-deploy
    owner: root
    group: root
    mode: 0440
  tags:
      - mightydok-common

- name: Add personal public ssh key file
  authorized_key:
    user: deploy
    state: present
    key: https://vokulov.ru/wp-content/uploads/publicsshkey
  tags:
      - mightydok-common
